dpi = "nodpi 120-640dpi"
patches-version = "dev"
cli-version = "dev"

[Instagram]
enabled = true
app-name = "Instagram"
patches-source = "crimera/piko"
brand = "Piko"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change version code' -OversionCode=2147483647"

[Twitter]
enabled = true
app-name = "X"
patches-source = "crimera/piko"
brand = "Piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/x-twitter"
version = "11.69.0-release.0"
arch = "arm64-v8a"
included-patches = "'Disunify xchat system' 'Dynamic color'"
excluded-patches= "'Bring back twitter' 'Pause search suggestions' 'Enable debug menu for posts' 'Enable PiP mode automatically' 'Hide community badges' 'Hide post metrics' 'Hide followed by context' 'Show sensitive media' 'Hide Community Notes' 'Export all activities'"
patcher-args = "-e 'Change version code' -OversionCode=2147483647"

[Letterboxd]
enabled = true
app-name = "Letterboxd"
patches-source = "RookieEnough/De-Vanced"
brand = "De-Vanced"
uptodown-dlurl = "https://letterboxd.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/letterboxd-limited/letterboxd/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=com.morphe.letterboxd.letterboxd"

[Google-Photos]
enabled = true
app-name = "Google Photos"
patches-source = "RookieEnough/De-Vanced"
brand = "De-Vanced"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
version = "auto"
arch = "arm64-v8a"
included-patches = "'Enable DCIM folders backup control'"
patcher-args = "-e 'Change package name' -OpackageName=app.morphe.android.photos"

[ProtonMail]
enabled = true
app-name = "Proton Mail"
patches-source = "RookieEnough/De-Vanced"
brand = "De-Vanced"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=ch.morphe.protonmail.android"

[YouTube]
enabled = true
app-name = "YouTube"
brand = "Morphe"
uptodown-dlurl = "https://youtube.en.uptodown.com/android/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "21.05.265"
arch = "arm64-v8a"
included-patches = "'Disable Play Store updates'"
patcher-args = "-e 'Change package name' -OpackageName=app.morphe.android.youtube -OcustomName=Youtube"

[Truecaller]
enabled = true
app-name = "Truecaller"
patches-source = "gitlab:Paresh-Maheshwari/paresh-patches"
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
# github-dlurl = "https://github.com/nvbangg/apks/releases/tag/com.truecaller"
version = "auto"
arch = "arm64-v8a"

[CamScanner]
enabled = true
app-name = "CamScanner"
patches-source = "hoo-dles/morphe-patches"
brand = "hoo-dles"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=com.morphe.intsig.camscanner"