cli-version = "dev"

[Instagram]
enabled = true
app-name = "Instagram"
brand = "piko"
uptodown-dlurl = "https://instagram.en.uptodown.com/android/"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change version code' -OversionCode=2147483647"
changelog-keywords = ["Instagram"]

[Instagram.patches]
"github:crimera/piko" = { version = "dev", exclude = ["Improve image viewing", "Unlock Plus benefits"] }

[Twitter]
enabled = true
app-name = "X"
brand = "piko"
uptodown-dlurl = "https://twitter.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
version = "11.99.0-release.1"
arch = "arm64-v8a"
patcher-args = "-e 'Change version code' -OversionCode=2147483647"
changelog-keywords = ["Twitter"]

[X.patches]
"github:crimera/piko" = { version = "dev", include = ["Disunify xchat system", "Dynamic color"], exclude = ["Pause search suggestions", "Show sensitive media"] }
"gitlab:inotia00/piko-shim" = []

[Letterboxd]
enabled = true
app-name = "Letterboxd"
brand = "de-vanced"
uptodown-dlurl = "https://letterboxd.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/letterboxd-limited/letterboxd/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=com.morphe.letterboxd.letterboxd"
changelog-keywords = ["letterboxd"]

[Letterboxd.patches]
"github:RookieEnough/De-Vanced" = []
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }

[Google-Photos]
enabled = true
app-name = "Google Photos"
brand = "de-vanced"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android/"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=app.morphe.android.photos"

[Google-Photos.patches]
"github:RookieEnough/De-Vanced" = [ "Enable DCIM folders backup control" ]
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }

[ProtonMail]
enabled = true
app-name = "Proton Mail"
brand = "de-vanced"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"
version = "auto"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=ch.morphe.protonmail.android"
changelog-keywords = ["Proton Mail"]

[ProtonMail.patches]
"github:RookieEnough/De-Vanced" = []
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }

[YouTube]
enabled = true
app-name = "YouTube"
brand = "morphe"
uptodown-dlurl = "https://youtube.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
version = "21.05.265"
arch = "arm64-v8a"
patcher-args = "-e 'Change package name' -OpackageName=app.morphe.android.youtube"
changelog-keywords = ["YouTube"]

[YouTube.patches]
"github:MorpheApp/morphe-patches" = { version = "dev" }

[Truecaller]
enabled = true
app-name = "Truecaller"
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
version = "auto"
arch = "arm64-v8a"
changelog-keywords = ["truecaller"]

[Truecaller.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }

[CamScanner]
enabled = true
app-name = "CamScanner"
brand = "hoo-dles"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android/"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator/"
version = "auto"
patcher-args = "-e 'Change package name' -OpackageName=com.morphe.intsig.camscanner"
changelog-keywords = ["CamScanner"]

[CamScanner.patches]
"github:hoo-dles/morphe-patches" = []
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }

[Realme-Link]
enabled = true
app-name = "Realme Link"
brand = "lyyako"
uptodown-dlurl = "https://realme-link.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/realme-mobile/realme-link/"
version = "auto"
changelog-keywords = []

[Realme-Link.patches]
"github:lyyako/realme-link-patches" = []
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }

[Tiktok]
enabled = true
app-name = "Tiktok"
brand = "icysymmetra"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
version = "auto"
arch = "arm64-v8a"
changelog-keywords = []

[Tiktok.patches]
"github:icysymmetra/tiktok-patches-for-morphe" = []
"github:MorpheApp/morphe-patches" = { version = "dev", include = ["Disable Play Store updates"] }