strict-sigcheck = false

[YouTube-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YT-Music-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit-Stable]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Reddit-Stable.patches]
"github:MorpheApp/morphe-patches" = []

[YouTube-Experimental]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
version = "21.24.360"

[YouTube-Experimental.patches]
"github:MorpheApp/morphe-patches" = []

[YT-Music-Experimental]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"
version = "9.22.53"

[YT-Music-Experimental.patches]
"github:MorpheApp/morphe-patches" = []

[Reddit-Experimental]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "2026.23.0"

[Reddit-Experimental.patches]
"github:MorpheApp/morphe-patches" = []

[X-Twitter]
brand = "piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[X-Twitter.patches]
"github:crimera/piko" = ["Browse tweet object", "Dynamic color"]
"gitlab:inotia00/piko-shim" = []

[Instagram]
brand = "piko"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
# uptodown-dlurl = "https://instagram.en.uptodown.com/android"
arch = "arm64-v8a"

[Instagram.patches]
"github:crimera/piko" = []

[Amazon-Music]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-music-discover-songs/"
uptodown-dlurl = "https://amazon-mp3.en.uptodown.com/android"

[Amazon-Music.patches]
"github:RookieEnough/De-Vanced" = []

[Amazon-Shopping]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
uptodown-dlurl = "https://amazon-shopping.en.uptodown.com/android"

[Amazon-Shopping.patches]
"github:RookieEnough/De-Vanced" = []

[Disney-Plus]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney/"
uptodown-dlurl = "https://disney-disneyplus.en.uptodown.com/android"

[Disney-Plus.patches]
"github:RookieEnough/De-Vanced" = []

[Facebook]
brand = "de-vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.katana"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
uptodown-durl = "https://facebook.en.uptodown.com/android"
arch = "both"

[Facebook.patches]
"github:RookieEnough/De-Vanced" = []

[Google-News]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
uptodown-dlurl = "https://google-play-newsstand.en.uptodown.com/android"

[Google-News.patches]
"github:RookieEnough/De-Vanced" = []

[Google-Photos]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Google-Photos.patches]
"github:RookieEnough/De-Vanced" = []

[Google-Recorder]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"
uptodown-dlurl = "https://opnemer.en.uptodown.com/android"
arch = "arm64-v8a"
skip-sigcheck = true

[Google-Recorder.patches]
"github:RookieEnough/De-Vanced" = []

[Icon-Pack-Studio]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
uptodown-dlurl = "https://icon-pack-studio.en.uptodown.com/android"

[Icon-Pack-Studio.patches]
"github:RookieEnough/De-Vanced" = []

[Inshorts]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2/"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
arch = "both"

[Inshorts.patches]
"github:RookieEnough/De-Vanced" = []

[Letterboxd]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/letterboxd/letterboxd/"
uptodown-dlurl = "https://letterboxd.en.uptodown.com/android"

[Letterboxd.patches]
"github:RookieEnough/De-Vanced" = []

[Messenger]
brand = "de-vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.facebook.orca"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-technologies-llc/messenger/"
# uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
arch = "both"

[Messenger.patches]
"github:RookieEnough/De-Vanced" = []

[Nothing-X]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nothing-technology-limited/ear-1/"
uptodown-dlurl = "https://nothing-x.en.uptodown.com/android"

[Nothing-X.patches]
"github:RookieEnough/De-Vanced" = []

[Peacock-TV]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/peacock-tv-llc/peacock-tv/"
uptodown-dlurl = "https://peacock-tv.en.uptodown.com/android"

[Peacock-TV.patches]
"github:RookieEnough/De-Vanced" = []

[Photomath]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-llc/photomath/"
uptodown-dlurl = "https://photomath.en.uptodown.com/android"

[Photomath.patches]
"github:RookieEnough/De-Vanced" = []

[Pixiv]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pixiv-inc/pixiv/"
uptodown-dlurl = "https://pixiv.en.uptodown.com/android"

[Pixiv.patches]
"github:RookieEnough/De-Vanced" = []

[Proton-Mail]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email/"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"

[Proton-Mail.patches]
"github:RookieEnough/De-Vanced" = []

[RAR]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/rar-lab/rar/"
uptodown-dlurl = "https://rar-for-android.en.uptodown.com/android"

[RAR.patches]
"github:RookieEnough/De-Vanced" = []

[Strava]
brand = "de-vanced"
uptodown-dlurl = "https://strava.en.uptodown.com/android"

[Strava.patches]
"github:RookieEnough/De-Vanced" = []

[Threads]
brand = "de-vanced"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/com.instagram.barcelona"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app/"
# uptodown-dlurl = "https://threads.en.uptodown.com/android"
arch = "both"

[Threads.patches]
"github:RookieEnough/De-Vanced" = []

[TikTok]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"

[TikTok.patches]
"github:RookieEnough/De-Vanced" = []

[Tumblr]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"

[Tumblr.patches]
"github:RookieEnough/De-Vanced" = []

[Twitch]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"

[Twitch.patches]
"github:RookieEnough/De-Vanced" = []

[Viber]
brand = "de-vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/viber-media-s-a-r-l/viber/"

[Viber.patches]
"github:RookieEnough/De-Vanced" = []

[AdGuard]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard/"
uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"
changelog-keywords = ["AdGuard"]

[AdGuard.patches]
"github:hoo-dles/morphe-patches" = []

[Busuu]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/busuu/busuu-learn-languages/"
uptodown-dlurl = "https://busuu.en.uptodown.com/android"
changelog-keywords = ["Busuu"]

[Busuu.patches]
"github:hoo-dles/morphe-patches" = []

[Cake]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cake-corp/cake-lesson-updates-every-day/"
uptodown-dlurl = "https://me-mycake.en.uptodown.com/android"
arch = "both"
changelog-keywords = ["Cake"]

[Cake.patches]
"github:hoo-dles/morphe-patches" = []

[CamScanner]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-information-co-ltd/camscanner-phone-pdf-creator/"
uptodown-dlurl = "https://camscanner.en.uptodown.com/android"
changelog-keywords = ["CamScanner"]

[CamScanner.patches]
"github:hoo-dles/morphe-patches" = []

[Duolingo]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo/"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
changelog-keywords = ["Duolingo"]

[Duolingo.patches]
"github:hoo-dles/morphe-patches" = []

[FotMob]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fotmob-as/fotmob-live-soccer-scores/"
uptodown-dlurl = "https://soccer-scores.en.uptodown.com/android"
changelog-keywords = ["FotMob"]

[FotMob.patches]
"github:hoo-dles/morphe-patches" = []

[HelloChinese]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hellochinese-learn-chinese-mandarin/hellochinese-learn-chinese/"
uptodown-dlurl = "https://hellochinese.en.uptodown.com/android"
changelog-keywords = ["HelloChinese"]

[HelloChinese.patches]
"github:hoo-dles/morphe-patches" = []

[ibis-Paint-X]
brand = "hoo-dles"
uptodown-dlurl = "https://ibispaint-x.en.uptodown.com/android"
changelog-keywords = ["Ibis Paint"]

[ibis-Paint-X.patches]
"github:hoo-dles/morphe-patches" = []

[Meme-Generator]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/zombodroid/meme-generator-free/"
uptodown-dlurl = "https://meme-generator-free.en.uptodown.com/android"
changelog-keywords = ["Meme Generator"]

[Meme-Generator.patches]
"github:hoo-dles/morphe-patches" = []

[Merriam-Webster]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/merriam-webster-inc/dictionary-merriam-webster/"
uptodown-dlurl = "https://merriam-webster.en.uptodown.com/android"
changelog-keywords = ["Merriam", "Webster"]

[Merriam-Webster.patches]
"github:hoo-dles/morphe-patches" = []

[MyFitnessPal]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal/"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"
changelog-keywords = ["MyFitnessPal"]

[MyFitnessPal.patches]
"github:hoo-dles/morphe-patches" = []

[Niagara-Launcher]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean/"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
changelog-keywords = ["Niagara Launcher"]

[Niagara-Launcher.patches]
"github:hoo-dles/morphe-patches" = []

[Nova-Launcher]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/teslacoil-software/nova-launcher/"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
changelog-keywords = ["Nova Launcher"]

[Nova-Launcher.patches]
"github:hoo-dles/morphe-patches" = []

[Pandora]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts/"
changelog-keywords = ["Pandora"]

[Pandora.patches]
"github:hoo-dles/morphe-patches" = []

[Podcast-Addict]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict/"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
changelog-keywords = ["Podcast Addict"]

[Podcast-Addict.patches]
"github:hoo-dles/morphe-patches" = []

[Prime-Video]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
arch = "arm64-v8a"
changelog-keywords = ["Prime Video"]

[Prime-Video.patches]
"github:hoo-dles/morphe-patches" = []

[Sleep-as-Android]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/urbandroid-team/sleep-as-android-sleep-cycle-tracker-smart-alarm/"
uptodown-dlurl = "https://sleep-as-android.en.uptodown.com/android"
changelog-keywords = ["Sleep as Android"]

[Sleep-as-Android.patches]
"github:hoo-dles/morphe-patches" = []

[Smart-Launcher-6]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher/"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
changelog-keywords = ["Smart Launcher"]

[Smart-Launcher-6.patches]
"github:hoo-dles/morphe-patches" = []

[Sofascore]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/sofascore/"
uptodown-dlurl = "https://sofascore.en.uptodown.com/android"
changelog-keywords = ["Sofascore"]

[Sofascore.patches]
"github:hoo-dles/morphe-patches" = []

[Solid-Explorer]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-file-manager/"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
changelog-keywords = ["Solid Explorer"]

[Solid-Explorer.patches]
"github:hoo-dles/morphe-patches" = []

[SoundCloud]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud/"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
changelog-keywords = ["SoundCloud"]

[SoundCloud.patches]
"github:hoo-dles/morphe-patches" = []

[Wallcraft]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds/"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
changelog-keywords = ["Wallcraft"]

[Wallcraft.patches]
"github:hoo-dles/morphe-patches" = []

[Windy]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windyty-se/windy-wind-waves-and-hurricanes-forecast/"
uptodown-dlurl = "https://windy-wind-waves-and-hurricanes-forecast.en.uptodown.com/android"
changelog-keywords = ["Windy"]

[Windy.patches]
"github:hoo-dles/morphe-patches" = []

[WPS-Office]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf/"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"
changelog-keywords = ["WPS Office"]

[WPS-Office.patches]
"github:hoo-dles/morphe-patches" = []

[Xodo]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/apryse-software-inc/xodo-pdf-reader-editor/"
uptodown-dlurl = "https://xodo-docs.en.uptodown.com/android"
arch = "both"
changelog-keywords = ["Xodo"]

[Xodo.patches]
"github:hoo-dles/morphe-patches" = []

[XRecorder]
brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder/"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
changelog-keywords = ["XRecorder"]

[XRecorder.patches]
"github:hoo-dles/morphe-patches" = []

[CREX]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cricket-exchange/cricket-exchange-live-score-analysis/"
uptodown-dlurl = "https://live-line-and-cricket-scores-cricket-exchange.en.uptodown.com/android"
changelog-keywords = ["CREX"]

[CREX.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Cricbuzz]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cricbuzz-com/cricbuzz-live-cricket-scores-news/"
uptodown-dlurl = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"
changelog-keywords = ["Cricbuzz"]

[Cricbuzz.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Document-Scanner]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lufick/document-scanner-pdf-creator/"
uptodown-dlurl = "https://doc-scanner.en.uptodown.com/android"
changelog-keywords = ["Document Scanner"]

[Document-Scanner.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Eyecon]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/eyecon-phone-dialer-contacts/eyecon-caller-id-spam-block/"
uptodown-dlurl = "https://eyecon-phone-dialer-and-cont-eyecon.en.uptodown.com/android"
changelog-keywords = ["Eyecon"]

[Eyecon.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Fing]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools/"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"
changelog-keywords = ["Fing"]

[Fing.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[JioHotstar]
brand = "paresh"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/in.startv.hotstar"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/hotstar-2/"
changelog-keywords = ["JioHotstar"]

[JioHotstar.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[MacroDroid]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/arlosoft/macrodroid-device-automation-2/"
uptodown-dlurl = "https://macrodroid.en.uptodown.com/android"
arch = "both"
changelog-keywords = ["MacroDroid"]

[MacroDroid.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Plus-Messenger]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/rafalense/plus-messenger/"
uptodown-dlurl = "https://telegram-plus.en.uptodown.com/android"
changelog-keywords = ["Plus Messenger"]

[Plus-Messenger.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Proton-VPN]
brand = "paresh"
github-dlurl = "https://github.com/nvbangg/builder-for-morphe/releases/tag/ch.protonvpn.android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn/"
# uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
skip-sigcheck = true
changelog-keywords = ["Proton VPN"]

[Proton-VPN.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Telegram]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version/"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
changelog-keywords = ["Telegram"]

[Telegram.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[TickTick]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner/"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
changelog-keywords = ["TickTick"]

[TickTick.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[Truecaller]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
changelog-keywords = ["Truecaller"]

[Truecaller.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[VN]
brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ubiquiti-labs-llc/vn-video-editor-maker-vlognow/"
uptodown-dlurl = "https://vn-video-editor.en.uptodown.com/android"
changelog-keywords = ["VN"]

[VN.patches]
"gitlab:Paresh-Maheshwari/paresh-patches" = []

[YouTube-Anddea]
brand = "anddea"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Anddea.patches]
"github:anddea/revanced-patches" = { exclude = ["Visual preferences icons for YouTube"] }

[YT-Music-Anddea]
brand = "anddea"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "both"

[YT-Music-Anddea.patches]
"github:anddea/revanced-patches" = { exclude = ["Visual preferences icons for YouTube Music"] }

[KakaoTalk]
brand = "ample"
apkmirror-dlurl = "https://www.apkmirror.com/apk/kakao-corp/kakaotalk/"
uptodown-dlurl = "https://kakaotalk.en.uptodown.com/android"
changelog-keywords = ["KakaoTalk"]

[KakaoTalk.patches]
"github:AmpleReVanced/revanced-patches" = []
