# Copyright (c) 2026 nvbangg (github.com/nvbangg)

name: Sync upstream

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync upstream

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: false

      - name: Check upstream
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPSTREAM_URL=$(gh repo view --json parent -q '.parent.url // "https://github.com/krvstek/uni-apks"')
          git remote add upstream "$UPSTREAM_URL"
          git fetch --no-tags upstream refs/heads/main:refs/remotes/upstream/main
          git fetch --no-tags origin refs/heads/main:refs/remotes/origin/main

          if [ "$(git rev-list --count origin/main..upstream/main)" -eq 0 ]; then
            echo "::notice title=Sync upstream::There were no new commits."
            exit 0
          fi

          echo "HAS_CHANGES=true" >> "$GITHUB_OUTPUT"

      - name: Sync upstream
        if: steps.check.outputs.HAS_CHANGES == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if ! git merge upstream/main --no-ff --no-commit; then
            echo "::warning title=Sync Upstream Failed::Unresolved conflicts detected or Insufficient permissions"
            exit 0
          fi

          git commit -m "Merge remote-tracking branch 'upstream/main'"
          git push
          echo "::notice title=Sync upstream::New commits were found and synced."
